name: Deploy to Cloudflare Pages

on:
    push:
        branches:
            - main
            - staging

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            BRANCH_NAME: ${{ github.ref_name }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: npm

            - name: Install dependencies
              run: npm install

            - name: Build app
              run: |
                if [ "$BRANCH_NAME" = "main" ]; then
                  npm run build:prod
                else
                  npm run build:test
                fi
                cp dist/index.html dist/404.html

            - name: Deploy to Cloudflare Pages (Production)
              if: ${{ env.BRANCH_NAME == 'main' }}
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy dist --project-name=subscription-app

            - name: Deploy to Cloudflare Pages (Staging)
              if: ${{ env.BRANCH_NAME == 'staging' }}
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy dist --project-name=subscription-app --branch=staging
