name: Deploy to Cloudflare Pages

on:
    push:
        branches:
            - main
            - staging

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
                  cache: npm

            - name: Install dependencies
              run: npm install

            - name: Build app
              run: |
                  if [ "${{ github.ref }}" = "refs/heads/main" ]; then
                    npm run build:prod
                  else
                    npm run build:test
                  fi
                  cp dist/index.html dist/404.html

            - name: Deploy to Cloudflare Pages
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: subscription-app
                  directory: dist
                  branch: ${{ github.ref_name == 'main' && 'main' || 'staging' }}
